#!/usr/bin/env python3
from concept_map import ConceptMap

def main():
    cmap = ConceptMap('test.json')
    #print(cmap)
    #print(cmap.relations('speedometer', 'odometer'))
    print(cmap.level_key_values('speedometer'))
    print(cmap.level_key_values('odometer'))
    diff, variables = cmap.difference('speedometer', 'odometer')
    for i, subdiff in enumerate(diff):
        print('Level {} : {}'.format(i, subdiff))
    print(variables.variables)

if __name__ == '__main__':
    main()
