#!/usr/bin/env python3
from lib import InstanceMap, FrameMap

from pprint import pprint

def main():
    imap = InstanceMap('data/test.json')
    pprint(imap.instances)

    frame = imap.create_frame('speedometer', 'odometer')
    frame.show()

    fmap = FrameMap()
    fmap.add(frame)

    print(fmap.get('odometer-speedometer'))
    print(fmap.get_all('speedometer'))

    imap = InstanceMap('data/blockworld.json')
    pprint(imap.instances)
    imap.update_map()
    pprint(imap.map)

if __name__ == '__main__':
    main()
