#!/usr/bin/env python3
from lib import State, FrameMap, Event, Memory

from pprint import pprint

def main():
    '''
    state = State('data/test.json')
    pprint(state.instances)
    state.update_map()
    print('State map:')
    pprint(state.map)
    print('Associations for direction')
    print(state.map['direction'])

    frame = state.create_frame('speedometer', 'odometer')
    print(frame)

    fmap = FrameMap()
    fmap.add(frame)

    print(fmap.get('odometer-speedometer'))
    print(fmap.get_all('speedometer'))
    '''

    state = State('data/blockworld.json')
    pprint(state.instances)
    state.update_map()
    print('State map:')
    pprint(state.map)
    print('Key map:')
    pprint(state.keymap)

    print(state.select(['red', 'pyramid']))
    print(state.select([('isa', 'pyramid'), ('color', 'red')]))

    memory = Memory(state)
    memory.act(['red', 'pyramid'], ['location'], {'on' : 'a'})
    print(memory)

if __name__ == '__main__':
    main()
