#!/usr/bin/env python3
import sys, json

def main(args):
    assert len(args) == 2
    textfile = args[0]
    jsonfile = args[1]
    concepts = dict()

    with open(textfile, 'r') as infile:
        lines = [line for line in infile]
    for line in lines:
        line = line.replace('.', '')
        name, relation, node = line.split()
        if name in concepts:
            subdict = concepts[name]
            if relation in subdict:
                if isinstance(subdict[relation], list):
                    subdict[relation].append(node)
                else:
                    subdict[relation] = [subdict[relation], node]
        else:
            concepts[name] = {relation : node}

    with open(jsonfile, 'w') as outfile:
        json.dump(concepts, outfile)

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
